server:
  servlet:
    context-path: /todo-list-mrv/api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: false
  main:
    banner-mode: "off"

  springdoc:
    api-docs:
      path: /api-docs