server:
  servlet:
    context-path: /todo-list-mrv/api/v1
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.86.219:3306/db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: false
  main:
    banner-mode: "off"

  springdoc:
    api-docs:
      path: /api-docs